#!/bin/sh -e

__disk_detail() {
  if [ $(uname) = "FreeBSD" -o $(uname) = "Darwin" ]; then
    df -h
  else
    df -h -P
  fi
}

__disk() {
  local use="" total=""
  if [ $(uname) = "FreeBSD" ]; then
    use=$(zpool list | tail -1 | awk '{ print $3 }')
    total=$(zpool list | tail -1 | awk '{ print $2 }')
  elif [ $(uname) = "Darwin" ]; then
    use=$(df -h "/" | tail -1 | awk '{ print $3 }' | sed 's/i$//')
    total=$(df -h "/" | tail -1 | awk '{ print $2 }' | sed 's/i$//')
  else
    use=$(df -h "/" | tail -1 | awk '{ print $3 }')
    total=$(df -h "/" | tail -1 | awk '{ print $2 }')
  fi
  color b m W; printf "%s/" "$use"; color -; color b m W; printf "%s" "$total"; color -;
}

# vi: syntax=sh ts=4 noexpandtab
