#!/bin/sh -e

__disk_detail() {
  df -h -P
}

__disk() {
  local out="" MP="" size="" free="" unit=""
  [ -z "$MONITORED_DISK" ] && MP="/" || MP="$MONITORED_DISK"
  case $MP in
    /dev/*) MP=$(awk '$1 == m { print $2; exit(0); }' "m=$MP" /proc/mounts);;
  esac

  if [ "$(uname)" = "FreeBSD" ]; then
    out=$(df -h | grep "${MP}$" | awk '{ printf("%s %s", $4, $2); }')
  else
    out=$({ df -h -P "$MP" 2>/dev/null || df -h "$MP"; } | awk 'END { printf("%s %s", $3, $2); }')
  fi
  
  set -- ${out}
  free=${1}; size=${2};
  free_unit=${free#${free%?}}
  free=${free%?};
  unit=${size#${size%?}}
  size=${size%?};
  case "$unit" in
    k*|K*) unit="$ICON_KB" ;;
    m*|M*) unit="$ICON_MB" ;;
    g*|G*) unit="$ICON_GB" ;;
    t*|T*) unit="$ICON_TB" ;;
  esac
  case "$free_unit" in
    k*|K*) free_unit="$ICON_KB" ;;
    m*|M*) free_unit="$ICON_MB" ;;
    g*|G*) free_unit="$ICON_GB" ;;
    t*|T*) free_unit="$ICON_TB" ;;
  esac
  [ -n "$size" ] || return
  color b m W; printf "%s%s/%s%s" "$free" "$free_unit" "$size" "$unit"; color --; 
}
